### ISSUE TITLE
Does it work with QC12.53?

### ISSUE THREAD

**Issue by ribalm** [hpalmtools/turtleALM#2]
Does it work with QC12.53?

**Comment by ojacques** [comment]
Hi @ribalm - have you tried? What is the issue?

**Comment by ribalm** [comment]
There is no special issue. I just want to know whether it will work with QC 12.53. If there is a clear answer that QC 12.53 is supported then I will try it.

**Comment by ojacques** [comment]
That should work just fine. Cheers!
